#!/usr/bin/env python3
"""brain_home.py — the vault's LANDING PAGE (Home.md at vault root), regenerated by both
scheduled runs. One glance answers: is the brain healthy, who is flagged, what came in
today, what does the board say, and where do I go from here.

Zones: auto content between markers; ## Notes below is never touched.
  python3 brain/brain_home.py --vault ~/Downloads/NFL-Brain [--repo PATH]
"""
import argparse, glob, json, os, re, sys
from datetime import datetime, date

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import brain_common as bc

MARK_A = "%% auto:home:begin — refreshed by brain_home.py; your notes go under ## Notes %%"
MARK_B = "%% auto:home:end %%"


def health_line(vault):
    p = os.path.join(vault, "_status", "last-run.md")
    if not os.path.exists(p):
        return "❓ no run card found — has the daily ingest ever run?"
    lines = open(p, encoding="utf-8").read().split("\n")
    call = next((l for l in lines if "[!" in l), "")
    stats = next((l for l in lines if l.strip().startswith("- **")), "")
    status = call.split("]", 1)[-1].strip() if call else "unknown"
    return f"{status}" + (f" · {stats.lstrip('- ').strip()}" if stats else "")


def availability_watch(repo, limit=10):
    smp = os.path.join(repo, "boom", "statmenu.json")
    if not os.path.exists(smp): return []
    sm = json.load(open(smp))
    rows = [(v["name"], v.get("adp") or 999, v["avail"]) for v in sm.values()
            if isinstance(v, dict) and v.get("avail") and v.get("name")]
    rows = [r for r in rows if r[1] < 150]
    rows.sort(key=lambda r: str(r[2].get("d", "")), reverse=True)
    return rows[:limit]


def todays_intake(vault):
    today = date.today().strftime("%Y-%m-%d")
    month = date.today().strftime("%Y-%m")
    tw = glob.glob(os.path.join(vault, "Tweets", month, f"{today}*.md"))
    srcs = sorted(glob.glob(os.path.join(vault, "Sources", "*.md")),
                  key=os.path.getmtime, reverse=True)[:3]
    return len(tw), [os.path.splitext(os.path.basename(s))[0] for s in srcs]


def board_top(repo, n=12):
    # the LIVE board lives in the bestball repo; Fantasy's copy is a stale snapshot
    p = os.path.expanduser("~/Downloads/bestball/draft_board_signals.csv")
    if not os.path.exists(p):
        p = os.path.join(repo, "draft_board_signals.csv")
    if not os.path.exists(p): return []
    import csv
    rows = []
    for r in csv.DictReader(open(p)):
        try: mr = int(float(r.get("merged_rank") or 0))
        except ValueError: continue
        if mr: rows.append((mr, r.get("name", ""), r.get("pos", ""), r.get("adp", "")))
    rows.sort()
    return rows[:n]


def folder_nav(vault):
    out = []
    for d, blurb in [("Players", "one dossier per player — model read, best/worst, full tweet & source trail"),
                     ("Concepts", "per-team playbooks — how to value & attack each team"),
                     ("Teams", "team entities — coaches, win totals, adds/losses"),
                     ("Coaches", "coach entities with scheme notes"),
                     ("Sources", "captured articles & video transcripts"),
                     ("Tweets", "raw tweet notes by month")]:
        n = len(glob.glob(os.path.join(vault, d, "**", "*.md"), recursive=True))
        out.append((d, n, blurb))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--vault", required=True)
    ap.add_argument("--repo", default=None)
    a = ap.parse_args()
    vault = os.path.expanduser(a.vault)
    repo = bc.repo_root(a.repo)

    L = [f"# 🧠 NFL Brain",
         f"*{datetime.now().strftime('%A %Y-%m-%d %H:%M')} — regenerated by every brain run*", ""]
    L += [f"**Last ingest:** {health_line(vault)}", ""]

    av = availability_watch(repo)
    if av:
        L.append("## ⚠ Availability watch (ADP < 150)")
        for name, adp, e in av:
            L.append(f"- [[{name}]] — {e.get('term','?')} ({e.get('n',1)}× · latest {e.get('d','?')}) · ADP {adp:.0f}")
        L.append("")

    n_tw, srcs = todays_intake(vault)
    L.append("## Today's intake")
    L.append(f"- **{n_tw}** tweets captured today · newest sources:")
    for s in srcs: L.append(f"    - [[{s}]]")
    L.append("")

    top = board_top(repo)
    if top:
        L.append("## Board top-12 (DK merged rank)")
        L.append("| # | Player | Pos | ADP |")
        L.append("|---|---|---|---|")
        for mr, nm, pos, adp in top:
            try: adp = f"{float(adp):.1f}"
            except (ValueError, TypeError): pass
            L.append(f"| {mr} | [[{nm}]] | {pos} | {adp} |")
        L.append("")

    L.append("## Navigate")
    L.append("| Folder | Notes | What's inside |")
    L.append("|---|---|---|")
    for d, n, blurb in folder_nav(vault):
        L.append(f"| `{d}/` | {n} | {blurb} |")
    L += ["", "**Draft-day loop:** ⌘C the DK board → `python3 draft_pick.py clip --seat rsbathla` "
              "(bestball repo) · strategies: `bestball/analysis/SLOT_STRATEGIES.md`", ""]

    block = MARK_A + "\n" + "\n".join(L) + "\n" + MARK_B
    p = os.path.join(vault, "Home.md")
    if os.path.exists(p):
        cur = open(p, encoding="utf-8").read()
        if MARK_A in cur and MARK_B in cur:
            pre, rest = cur.split(MARK_A, 1); _, post = rest.split(MARK_B, 1)
            new = pre + block + post
        else:
            new = block + "\n\n" + cur   # preserve any hand-made content below
    else:
        new = block + "\n\n## Notes\n%% yours — never touched by the generator %%\n"
    open(p, "w", encoding="utf-8").write(new)
    bc.log(f"home: Home.md refreshed ({len(av)} availability flags · {n_tw} tweets today)")
    print(json.dumps({"avail": len(av), "tweets_today": n_tw}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
