#!/usr/bin/env python3
"""brain_warroom.py v2 — the WAR ROOM as a DRILL-DOWN knowledge atlas: a single
self-contained HTML app (vanilla JS, hash routing, no CDNs) for HOLISTIC understanding
of the whole knowledge base. Not a draft tool. Regenerated by both scheduled runs;
every entity deep-links into Obsidian via obsidian:// URIs.

Routes:
  #/               TEAMS tab — 32 team cards (coaches w/ NEW marks, win total, identity, lamps)
  #/today          the v1 panels — status rail · threat board · discourse radar ·
                   most discussed · fresh theses · newest sources · rooms
  #/team/<ABBR>    team room — identity & scheme · roster changes · personnel (2025 mix +
                   2026 projection + per-player FP splits) · defensive identity · environment ·
                   full ADP-sorted roster
  #/player/<slug>  dossier — facts · quant strip · funnels · personnel reliance · intel
                   (semantic-tagged tweets + forward claims) · obsidian footer

  python3 brain/brain_warroom.py --vault ~/Downloads/NFL-Brain [--repo PATH]
Output: <vault>/warroom.html  (ONE embedded JSON payload; graceful on missing files)
"""
import argparse, glob, html, json, os, re, sys
from collections import Counter
from datetime import datetime, date, timedelta

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import brain_common as bc

VAULT_NAME = "NFL-Brain"
TW_CAP, TW_TXT = 8, 300          # per-player tweet trim (payload budget)

# ---------------------------------------------------------------- name conventions
def fn(n):
    """repo-wide normalized-name convention (matches statmenu/fp_personnel/player_funnels keys)."""
    n = str(n).strip().lower()
    n = re.sub(r"\s+(jr|sr|ii|iii|iv|v)\.?$", "", n)
    return n.replace(".", "").replace("'", "").replace("-", " ")

def rslug(n):
    """url-safe route slug (for #/player/<slug>). bc.slug stays the obsidian filename."""
    s = re.sub(r"[^a-z0-9 ]", "", fn(n))
    return re.sub(r"\s+", "-", s.strip()) or "unknown"

# ---------------------------------------------------------------- loaders (graceful)
def jload(*parts):
    p = os.path.join(*parts)
    try:
        return json.load(open(p, encoding="utf-8")) if os.path.exists(p) else None
    except Exception as e:
        bc.log(f"warroom: could not parse {p}: {e}")
        return None

# ---------------------------------------------------------------- v1 status helpers (reused)
def run_status(vault):
    p = os.path.join(vault, "_status", "last-run.md")
    if not os.path.exists(p): return ("red", "no run card — has the ingest ever run?")
    txt = open(p, encoding="utf-8").read()
    call = next((l for l in txt.split("\n") if "[!" in l), "")
    msg = call.split("]", 1)[-1].strip() if call else "unknown"
    lamp = "red" if "❌" in call or "danger" in call else ("amber" if "⚠" in call else "green")
    stats = next((l.lstrip("- ").strip() for l in txt.split("\n") if l.strip().startswith("- **")), "")
    return (lamp, (msg + (" · " + stats if stats else "")).replace("**", ""))

def weekly_status(vault):
    p = os.path.join(vault, "_status", "weekly.log")
    if not os.path.exists(p): return ("amber", "weekly model refresh: never run")
    txt = open(p, encoding="utf-8", errors="replace").read()
    runs = re.findall(r"===== WEEKLY MODEL REFRESH (.+?) ·", txt)
    if not runs: return ("amber", "weekly model refresh: never run")
    return ("green", f"weekly quant refresh — last: {runs[-1].strip()}")

def lines_status(repo):
    p = os.path.join(repo, "ffdataroma_draft_guide_export/ffdataroma/csv/weekly-vegas-lines.csv")
    if not os.path.exists(p): return ("amber", "vegas lines: source missing")
    d = (datetime.now() - datetime.fromtimestamp(os.path.getmtime(p))).days
    return ("green" if d <= 14 else "amber", f"vegas lines: {d}d old")

def fm_field(head, key):
    m = re.search(rf"^{key}:\s*(.+)$", head, re.M)
    return m.group(1).strip() if m else ""

def todays_tweets(vault):
    today = date.today().strftime("%Y-%m-%d"); month = date.today().strftime("%Y-%m")
    out = []
    for p in glob.glob(os.path.join(vault, "Tweets", month, f"{today}*.md")):
        txt = open(p, encoding="utf-8", errors="replace").read()
        parts = txt.split("---", 2)
        if len(parts) < 3: continue
        head = parts[1]
        ments = re.findall(r"\[\[([^\]]+)\]\]", head.split("mentions:", 1)[1].split("\n", 1)[0]) if "mentions:" in head else []
        out.append({"url": fm_field(head, "url"), "mentions": ments})
    return out

_TEAM_LAST_WORDS = ("Ravens","Bengals","Lions","Bears","Chiefs","Rams","Giants","Jets","Eagles",
    "Cowboys","Packers","49ers","Seahawks","Broncos","Patriots","Bills","Dolphins","Texans","Colts",
    "Jaguars","Titans","Browns","Steelers","Chargers","Raiders","Commanders","Saints","Falcons",
    "Panthers","Buccaneers","Cardinals","Vikings")

# ---------------------------------------------------------------- payload builders
def _game_env(gs):
    """per-team underdog count + avg implied across all simmed weeks (v1-style calc,
    same as brain_concepts._environment)."""
    env = {}
    for wk in (gs.get("weeks") or {}).values():
        for g in wk.get("games", []):
            v = g.get("vegas") or {}
            for ab in g.get("teams", []):
                e = env.setdefault(ab, {"dogs": 0, "gms": 0, "imps": []})
                imp = (v.get("imp") or {}).get(ab)
                if imp: e["imps"].append(imp)
                fav = v.get("spread_fav"); line = -v.get("spread", 0) if fav == ab else v.get("spread", 0)
                if line > 0: e["dogs"] += 1
                e["gms"] += 1
    return {ab: {"dogs": e["dogs"], "gms": e["gms"],
                 "imp": round(sum(e["imps"]) / len(e["imps"]), 1) if e["imps"] else None}
            for ab, e in env.items()}

def _trim(s, n):
    s = str(s or "")
    return s if len(s) <= n else s[:n - 1].rstrip() + "…"

# coverage vocabulary — what counts as a "coverage scheme" report from the brain.
# CONTEXTUAL on purpose: bare man/zone/press/nickel/dime fire on idioms ("head man",
# "stopped on a dime", "press conference") and run-game text ("zone-blocking").
COV_RE = re.compile(r"""
    \bman[- ]to[- ]man\b | \bman\s+coverage\b | \bpress\s+man\b | \bman[- ]heavy\b
  | \bman\s+rate\b | \b(?:in|vs\.?|against|play(?:s|ing)?)\s+man\b
  | \bzone\s+coverage\b | \bzone\s+rate\b | \bmatch\s+zone\b | \bzone[- ]heavy\b
  | \b(?:in|vs\.?|against|play(?:s|ing)?)\s+zone\b
  | \btwo[- ]high\b | \bsingle[- ]high\b | \bcover\s?[0-6]\b
  | \bquarters\s+coverage\b | \bpalms\b | \bmatch\s+coverage\b
  | \bpress\s+coverage\b | \bpress\s+rate\b
  | \bblitz | \bsim(?:ulated)?\s+pressure\b | \bshell\b
  | \bnickel\s+(?:package|defense|personnel|corner|back)\b
  | \bdime\s+(?:package|defense|personnel|back)\b
""", re.I | re.X)

def build_dc_intel(cs26, bi):
    """per new-DC team: coverage-vocab-matched intel from brain_intel coaches[dc].tw/.src26
    + teams[team].tw — deduped, newest first, top 3 kept (full match count reported)."""
    coaches = bi.get("coaches") or {}
    by_abbr = {e.get("abbr"): e for e in (bi.get("teams") or {}).values()
               if isinstance(e, dict) and e.get("abbr")}
    out = {}
    for ab, e in cs26.items():
        if not (isinstance(e, dict) and e.get("dc_new")): continue
        pool = []
        ce = coaches.get(e.get("dc_name") or "") or {}
        for t in (ce.get("tw") or []):
            pool.append({"d": t.get("d", ""), "a": t.get("a", ""), "t": t.get("t", ""), "u": t.get("u", "")})
        for s in (ce.get("src26") or []):
            pool.append({"d": s.get("d", ""), "a": s.get("o", ""), "t": s.get("t", ""), "u": ""})
        for t in ((by_abbr.get(ab) or {}).get("tw") or []):
            pool.append({"d": t.get("d", ""), "a": t.get("a", ""), "t": t.get("t", ""), "u": t.get("u", "")})
        hits, seen = [], set()
        for it in pool:
            txt = str(it.get("t") or "")
            if not COV_RE.search(txt): continue
            dup = it.get("u") or txt[:80]
            if dup in seen: continue
            seen.add(dup)
            hits.append(it)
        hits.sort(key=lambda x: str(x.get("d", "")), reverse=True)
        out[ab] = {"n": len(hits),
                   "items": [{"d": h["d"], "a": h["a"], "t": _trim(h["t"], 200)} for h in hits[:3]]}
    return out

def build_players(sm, intel, sem, pfun, fp_players, sfit, cs26, crsp, dfs_drv):
    """players payload keyed by route slug."""
    out = {}
    for key, v in sm.items():
        if not (isinstance(v, dict) and v.get("name")): continue
        name = v["name"]; slug = rslug(name)
        it = intel.get(fn(name)) or {}
        # newest tweets, semantic-tagged via url lookup
        tws = sorted((it.get("tw") or []), key=lambda t: str(t.get("d", "")), reverse=True)[:TW_CAP]
        tw = [{"d": t.get("d", ""), "a": t.get("a", ""), "t": _trim(t.get("t"), TW_TXT),
               "u": t.get("u", ""), "s": (sem.get(t.get("u", "")) or {}).get("s", "")} for t in tws]
        fwd = [{"d": f.get("d", ""), "s": str(f.get("s", "")), "t": _trim(f.get("t"), TW_TXT)}
               for f in (it.get("fwd") or [])]
        cs = v.get("cspec") or {}
        pfn = pfun.get(key) or {}
        al = pfn.get("alignment_funnel") or {}
        fp = fp_players.get(key) or {}
        sf = sfit.get(key) or {}
        cov = None
        if sf:
            cov = {
                "b": {k: {"p": b.get("pctl"), "r": b.get("rte")}
                      for k, b in (sf.get("buckets") or {}).items()},
                "el": [{"k": e.get("key"), "p": e.get("pctl"), "y": e.get("yprr"), "r": e.get("rte")}
                       for e in (sf.get("elite") or [])],
                "wk": [{"k": e.get("key"), "p": e.get("pctl"), "y": e.get("yprr"), "r": e.get("rte")}
                       for e in (sf.get("weak") or [])],
                "fit": {"s": sf.get("season"), "r": sf.get("regular"), "p": sf.get("playoff")},
                "pw": [{"wk": w.get("wk"), "opp": w.get("opp"), "fit": w.get("fit"),
                        "why": _trim(w.get("why"), 160), "nd": 1 if w.get("new_dc") else 0,
                        # the man-rate tendency the fit was priced against (coordinator_scheme_2026)
                        "ma": (cs26.get(w.get("opp")) or {}).get("man_rate_adj"),
                        "cf": (cs26.get(w.get("opp")) or {}).get("conf")}
                       for w in (sf.get("playoff_weeks") or [])],
            }
        cr = crsp.get(key)
        sch = None
        if cr:
            def _schrow(s, d):
                row = {"k": s, "rte": d.get("rte"), "y": d.get("yprr"),
                       "p": d.get("pctl"), "q": 1 if d.get("q") else 0}
                a = d.get("adv2025")
                if isinstance(a, dict):  # 2025-vintage DK-scoped block (build_coverage_adv2025.py)
                    row["a"] = {"r": a.get("rte"), "t": a.get("tprr"), "sw": a.get("sep_win"),
                                "ad": a.get("adot"), "cc": a.get("ctc"), "dk": a.get("dk_rr")}
                return row
            sch = sorted((_schrow(s, d) for s, d in (cr.get("schemes") or {}).items()
                          if isinstance(d, dict)),
                         key=lambda r: -(r["rte"] or (r.get("a") or {}).get("r") or 0))
        # man/zone OUTCOME split from the dfs_scenarios drivers (EPA/target man vs zone +
        # man-route exposure) — a rate needs its exposure alongside it (C8)
        drv = dfs_drv.get(fn(name)) or {}
        mz = {"m": drv.get("rec_epa_per_tgt_man"), "z": drv.get("rec_epa_per_tgt_zone"),
              "d": drv.get("rec_man_zone_delta"), "sh": drv.get("man_route_sh")}
        if all(v is None for v in mz.values()):
            mz = None
        out[slug] = {
            "n": name, "pos": v.get("pos", ""), "tm": v.get("team", ""),
            "adp": round(v["adp"], 1) if isinstance(v.get("adp"), (int, float)) else None,
            "av": v.get("avail") or None,
            "os": bc.slug(name, 80),
            "sig": it.get("n_sig", 0), "noise": it.get("n_noise", 0),
            "sched": v.get("sched") or {},
            "cs": ({"best": cs.get("best"), "pctl": cs.get("pctl"), "routes": cs.get("routes"),
                    "pctls": cs.get("pctls")} if cs else None),
            "q": {"bb": v.get("base_blended"), "boom": v.get("base_boom"),
                  "ng": v.get("n_games"), "bg": v.get("boom_games"),
                  "fus": v.get("fus") or {}, "use": v.get("usage") or {},
                  "adot": v.get("adot") or {}, "rz": v.get("rz") or {},
                  "env": v.get("team_env") or {}},
            "fun": ({"recv": pfn.get("recv"), "rush": pfn.get("rush"),
                     "mix": al.get("mix"), "home": al.get("home"), "wf": al.get("wins_from"),
                     "yprr_by": al.get("yprr_by"), "sep_by": al.get("sep_by")} if pfn else None),
            "fp": ({"mix": fp.get("personnel_mix"), "hs": fp.get("heavy_share"),
                    "routes": fp.get("routes"), "t11": fp.get("tprr_11"), "d11": fp.get("dkfp_rr_11"),
                    "th": fp.get("tprr_heavy"), "dh": fp.get("dkfp_rr_heavy")} if fp else None),
            "tw": tw, "fwd": fwd, "cov": cov, "sch": sch, "mz": mz,
        }
    return out

def build_teams(sm, players_by_slug, off, sch, cc, wt, pers, proj, fp_players, dprof, ds, ngs, tc, proe, genv, cs26, dci):
    teams = {}
    for ab, names in sorted(bc._TEAMS.items()):
        o = off.get(ab) or {}
        s2 = sch.get(ab) or {}
        c = cc.get(ab) or {}
        w = wt.get(ab) or {}
        pe = pers.get(ab) or {}
        pj = proj.get(ab) or {}
        dp = dprof.get(ab) or {}
        sp = ds.get(ab) or {}
        ng = ((ngs.get(ab) or {}).get("pass") or {})
        ce = tc.get(ab) or {}
        pr = proe.get(ab) or {}
        ev = genv.get(ab) or {}
        fpaa = dp.get("dvoa_fpaa") or {}
        drv = sorted(((k, v) for k, v in (ce.get("drivers") or {}).items()
                      if isinstance(v, (int, float)) and v > 0), key=lambda x: -x[1])[:3]
        pjp = pj.get("projection_2026") or {}
        roster = []
        for s, p in players_by_slug.items():
            if p["tm"] == ab:
                roster.append([s, p["n"], p["pos"], p["adp"], 1 if p["av"] else 0, p["sig"], p["noise"]])
        roster.sort(key=lambda r: (r[3] is None, r[3] if r[3] is not None else 9999))
        fpp = sorted(({"k": None, "n": k2,
                       "pos": v2.get("pos", ""), "routes": v2.get("routes"), "hs": v2.get("heavy_share"),
                       "t11": v2.get("tprr_11"), "d11": v2.get("dkfp_rr_11"),
                       "th": v2.get("tprr_heavy"), "dh": v2.get("dkfp_rr_heavy")}
                      for k2, v2 in fp_players.items()
                      if v2.get("team") == ab and (v2.get("routes") or 0) >= 150),
                     key=lambda r: -(r["routes"] or 0))
        # map fp key (fn-name) back to route slug + display name when the player is in statmenu
        for r in fpp:
            s = rslug(r["n"])
            if s in players_by_slug:
                r["k"] = s; r["n"] = players_by_slug[s]["n"]
            else:
                r["n"] = r["n"].title()
        teams[ab] = {
            "name": names[0],
            "hc": w.get("hc", ""), "oc": w.get("oc", ""), "dc": w.get("dc", ""),
            "wt": w.get("win_total_2026", o.get("environment", {}).get("win_total")),
            "ident": o.get("identity", ""), "snote": o.get("scheme_note", ""),
            "outlook": w.get("offense_outlook", ""),
            "pc": s2.get("playcaller") or o.get("playcaller", ""),
            "defc": s2.get("dc", ""), "dnote": s2.get("def_note", ""),
            "cc": {k: c[k] for k in ("oc_new", "oc_name", "dc_new", "dc_name", "dc_scheme",
                                     "dc_title", "def_caller", "source", "dc_source", "src") if c.get(k) is not None},
            "adds": w.get("key_additions") or [], "losses": w.get("key_losses") or [],
            "pers": {"heavy": pe.get("heavy_2025"), "pa": pe.get("pa_2025"),
                     "motion": pe.get("motion_2025"), "pace": pe.get("pace_2025"),
                     "rank": pe.get("heavy_rank_2025"), "fph": pe.get("fp_heavy_rate_2025"),
                     "mix": pe.get("fp_personnel_mix")},
            "proj": ({"dir": pjp.get("heavy_direction"), "emph": pjp.get("emphasis") or [],
                      "why": pjp.get("rationale", ""),
                      "base": pj.get("baseline_2025") or {},
                      "oc26": pj.get("oc_2026", ""),
                      "ev": [{"c": _trim(e.get("claim"), 400), "s": e.get("source", "")}
                             for e in (pj.get("evidence") or [])]} if pj else None),
            "fpp": fpp,
            "dp": {"atk": [k.upper() for k, x in fpaa.items() if isinstance(x, (int, float)) and x >= 1.5],
                   "avd": [k.upper() for k, x in fpaa.items() if isinstance(x, (int, float)) and x <= -1.5],
                   "fpaa": fpaa, "fun": dp.get("funnels") or [],
                   "lean": dp.get("lean_2026"), "cb1": dp.get("cb1")},
            "sp": {"shell": sp.get("shell") or {}, "bypos": sp.get("by_pos") or {},
                   "units": sp.get("units") or {},
                   "vs": {lbl: {"soft": (sp.get(k) or {}).get("softness_pctl"),
                                "ypr": (sp.get(k) or {}).get("allowed_ypr")}
                          for lbl, k in (("man", "vs_man"), ("zone", "vs_zone"),
                                         ("deep", "deep"), ("short", "short"))
                          if isinstance(sp.get(k), dict)}},
            "ngs": {k: {"soft": x.get("soft_pctl"), "sep": x.get("sep_pctl"), "epa": x.get("epa_pass")}
                    for k, x in ng.items() if k != "ALL" and isinstance(x, dict)},
            "env": {"ceil": ce.get("ceiling_score"), "tier": ce.get("tier"), "rank": ce.get("rank"),
                    "drv": [[k, round(v, 3)] for k, v in drv], "flags": ce.get("flags") or [],
                    "proe": pr.get("proe_2026"), "proe25": pr.get("proe_2025"), "pnote": pr.get("note", ""),
                    "dogs": ev.get("dogs"), "gms": ev.get("gms"), "imp": ev.get("imp")},
            "cs26": ({"m25": (cs26.get(ab) or {}).get("man_rate_2025"),
                      "ma": (cs26.get(ab) or {}).get("man_rate_adj"),
                      "s25": (cs26.get(ab) or {}).get("sack_rate_2025"),
                      "sa": (cs26.get(ab) or {}).get("sack_rate_adj"),
                      "dcn": 1 if (cs26.get(ab) or {}).get("dc_new") else 0,
                      "dc": (cs26.get(ab) or {}).get("dc_name"),
                      "conf": (cs26.get(ab) or {}).get("conf")} if cs26.get(ab) else None),
            "dci": dci.get(ab),
            "avct": sum(1 for r in roster if r[4]),
            # lamp fires only on a projected personnel SHIFT (up/down) — every team has a
            # direction field, so bare existence would light all 32 cards
            "schfl": 1 if pjp.get("heavy_direction") in ("up", "down") else 0,
            "roster": roster,
        }
    return teams

def build_today(vault, repo, sm, bi, sem, cs26, dci):
    lamps = [list(run_status(vault)), list(weekly_status(vault)), list(lines_status(repo))]
    threats = sorted(((v["name"], v["avail"]) for v in sm.values()
                      if isinstance(v, dict) and v.get("avail") and v.get("name")),
                     key=lambda r: str(r[1].get("d", "")), reverse=True)[:14]
    threat_rows = [{"n": n, "k": rslug(n), "term": e.get("term", "?"), "x": e.get("n", 1),
                    "d": str(e.get("d", "")),
                    "sev": "red" if any(w in str(e.get("term", "")) for w in ("acl", "achilles", "fractur", "surger")) else "amber"}
                   for n, e in threats]
    tws = todays_tweets(vault)
    lab = Counter(sem.get(t["url"], {}).get("s", "unlabeled") for t in tws if t["url"])
    ment = Counter(m for t in tws for m in t["mentions"]
                   if " " in m and m.split()[-1] not in _TEAM_LAST_WORDS)
    cutoff = (date.today() - timedelta(days=10)).strftime("%Y-%m-%d")
    theses = []
    for name, e in (bi.get("players") or {}).items():
        for f in e.get("fwd", []):
            if str(f.get("d", "")) >= cutoff and "Signal" in str(f.get("s", "")):
                theses.append([f.get("d", ""), name, rslug(name), _trim(f.get("t"), 220)])
    theses.sort(reverse=True)
    srcs = sorted(glob.glob(os.path.join(vault, "Sources", "*.md")), key=os.path.getmtime, reverse=True)[:5]
    rooms = [("Players", "player dossiers"), ("Concepts", "team playbooks"), ("Teams", "team entities"),
             ("Coaches", "coaches"), ("Sources", "articles & transcripts"), ("Tweets", "raw tweets")]
    counts = (bi.get("_meta") or {}).get("counts", {})
    return {
        "lamps": lamps, "threats": threat_rows, "n_tw": len(tws),
        "radar": dict(lab), "most": [[m, rslug(m), c] for m, c in ment.most_common(8)],
        "theses": theses[:6],
        "sources": [os.path.splitext(os.path.basename(s))[0] for s in srcs],
        "rooms": [[d, len(glob.glob(os.path.join(vault, d, "**", "*.md"), recursive=True)), b] for d, b in rooms],
        "counts": counts,
        "n_sig_players": sum(1 for e in (bi.get("players") or {}).values() if e.get("n_sig")),
        "intel_gen": str((bi.get("_meta") or {}).get("generated", ""))[:16],
        # league-wide "where will coverage schemes meaningfully change" table, |man delta| desc
        "scheme_watch": sorted(
            ([ab, e.get("dc_name") or "?", e.get("man_rate_2025"), e.get("man_rate_adj"),
              e.get("conf") or "?", (dci.get(ab) or {}).get("n", 0)]
             for ab, e in cs26.items() if isinstance(e, dict) and e.get("dc_new")),
            key=lambda r: -abs((r[3] or 0) - (r[2] or 0))),
    }

# ---------------------------------------------------------------- html shell
HTML = r"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Brain. — War Room</title><style>
:root{--ink:#111;--paper:#FFF;--hair:#EAEAEA;--lab:#999;--mut:#666;--red:#E30613;--green:#1F9D55;--amber:#F0A500;--track:#F1F1F1}
*{box-sizing:border-box}
body{margin:0;font:14px/1.55 'Helvetica Neue',Helvetica,-apple-system,sans-serif;color:var(--ink);
background:var(--paper);min-height:100vh;padding:44px 32px 90px;font-variant-numeric:tabular-nums}
a{color:inherit;text-decoration:none;border-bottom:1px solid #CFCFCF;cursor:pointer}
a:hover,a:focus-visible{color:var(--red);border-bottom-color:var(--red);outline:none}
.wrap{max-width:1180px;margin:0 auto}
h1{font-size:23px;font-weight:700;letter-spacing:-.02em;margin:0}
h1 .dot{color:var(--red)}
.hdr{display:flex;align-items:baseline;gap:18px;flex-wrap:wrap;margin-bottom:0;padding-bottom:14px;border-bottom:2px solid var(--ink)}
.stamp{font-size:10px;letter-spacing:.16em;color:var(--lab);text-transform:uppercase}
.tabs{display:flex;gap:26px;margin:0 0 30px;border-bottom:1px solid var(--hair)}
.tab{padding:12px 1px 10px;font-size:10px;letter-spacing:.18em;text-transform:uppercase;color:var(--lab);
border-bottom:2px solid transparent;margin-bottom:-1px}
.tab.on{color:var(--ink);border-bottom-color:var(--red)}
.crumb{font-size:10px;letter-spacing:.14em;color:var(--lab);margin:0 0 20px;text-transform:uppercase}
.crumb a{border-bottom:none}
.rail{display:flex;gap:28px;flex-wrap:wrap;margin:0 0 28px;font-size:12px}
.lamp{width:8px;height:8px;border-radius:50%;display:inline-block;flex:none}
.lamp.sm{width:7px;height:7px}
.lamp-row{display:flex;align-items:center;gap:8px}
.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:14px}
.panel{background:var(--paper);border:1px solid var(--hair);padding:17px 19px}
.panel h2{font-size:10px;font-weight:600;letter-spacing:.17em;text-transform:uppercase;color:var(--lab);margin:0 0 12px}
.c6{grid-column:span 6}.c4{grid-column:span 4}.c8{grid-column:span 8}.c12{grid-column:span 12}
@media(max-width:880px){.c6,.c4,.c8{grid-column:span 12}body{padding:24px 16px 60px}}
.row{display:flex;align-items:center;gap:9px;padding:5px 0;border-bottom:1px solid var(--hair);font-size:12.5px}
.row:last-child{border-bottom:none}
.who{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.what{color:var(--mut);font-size:12px}
.when{font-size:11px;color:var(--lab);letter-spacing:.05em}
.mut{color:var(--lab);font-size:12.5px}
.bar-row{display:flex;align-items:center;gap:10px;padding:4px 0;font-size:12px}
.bl{width:74px;color:var(--mut)}
.bar{flex:1;height:5px;background:var(--track)}
.bar i{display:block;height:100%}
.bv{width:30px;text-align:right;font-weight:600;font-size:12px}
.chip{display:inline-block;border:1px solid var(--hair);padding:2px 9px;margin:3px 4px 0 0;font-size:11.5px}
.chip b{font-weight:600;margin-left:3px}
.chip.g b{color:var(--green)}.chip.r b{color:var(--red)}
.chip.a{border-color:var(--amber);color:#B67E00}
.thesis{padding:7px 0;border-bottom:1px solid var(--hair);font-size:12.5px;line-height:1.5}
.thesis:last-child{border-bottom:none}
.rooms{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}
.room{display:flex;flex-direction:column;gap:2px;border:1px solid var(--hair);padding:11px 13px;border-bottom:1px solid var(--hair)}
.room b{font-size:13px;font-weight:600}
.rc{font-size:19px;font-weight:700;letter-spacing:-.02em}
.rb{font-size:10.5px;color:var(--lab)}
.foot{margin-top:26px;padding-top:12px;border-top:1px solid var(--hair);font-size:11px;color:var(--lab);display:flex;gap:20px;flex-wrap:wrap}
/* team cards */
.cards{display:grid;grid-template-columns:repeat(auto-fill,minmax(258px,1fr));gap:12px}
.tcard{display:block;border:1px solid var(--hair);padding:14px 16px;border-bottom:1px solid var(--hair);transition:border-color .12s}
.tcard:hover{border-color:var(--ink)}
.tc-top{display:flex;align-items:baseline;gap:9px}
.tc-ab{font-size:16px;font-weight:700;letter-spacing:-.01em}
.tc-nm{flex:1;font-size:11.5px;color:var(--mut);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.tc-wt{font-size:12px;font-weight:600}
.tc-co{font-size:11px;color:var(--lab);margin:7px 0 5px;line-height:1.55}
.tc-co b{color:var(--ink);font-weight:500}
.new{color:var(--red);font-size:8.5px;font-weight:700;letter-spacing:.1em;border:1px solid var(--red);
padding:1px 3px;margin-left:4px;vertical-align:1px}
.tc-id{font-size:11.5px;color:var(--mut);line-height:1.5;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;min-height:34px}
.tc-lamps{display:flex;gap:15px;margin-top:9px;font-size:10.5px;color:var(--lab);align-items:center}
/* sections + tables */
.sect{margin-bottom:14px}
.tbl{width:100%;border-collapse:collapse;font-size:12.5px}
.tbl th{font-size:9.5px;font-weight:600;letter-spacing:.13em;text-transform:uppercase;color:var(--lab);
text-align:left;padding:4px 8px 6px;border-bottom:1px solid var(--ink)}
.tbl td{padding:5px 8px;border-bottom:1px solid var(--hair)}
.tbl tr:last-child td{border-bottom:none}
.tbl .num{text-align:right;font-variant-numeric:tabular-nums}
.tbl th.num{text-align:right}
.badge{display:inline-block;border:1px solid var(--hair);padding:1px 7px;font-size:9px;font-weight:600;letter-spacing:.12em;text-transform:uppercase}
.badge.amber{color:#B67E00;border-color:var(--amber)}
.badge.red{color:var(--red);border-color:var(--red)}
.badge.green{color:var(--green);border-color:var(--green)}
.badge.blue{color:var(--mut)}
.kv{display:flex;flex-wrap:wrap;gap:10px 26px;font-size:12.5px;margin:4px 0}
.kv .k{color:var(--lab);font-size:9.5px;letter-spacing:.13em;text-transform:uppercase;display:block;margin-bottom:1px}
.kv .v{font-size:15px;font-weight:600;letter-spacing:-.01em}
.kv .v small{font-size:10px;font-weight:400;color:var(--lab);letter-spacing:0}
.note{font-size:12.5px;line-height:1.6;color:var(--ink)}
.note b{font-weight:600}
.sublab{font-size:9.5px;font-weight:600;letter-spacing:.14em;text-transform:uppercase;color:var(--lab);margin:14px 0 6px}
.sublab:first-child{margin-top:0}
.bx{width:64px;text-align:right;font-size:11px;color:var(--lab)}
.ev{border-left:2px solid var(--hair);padding:4px 0 4px 11px;margin:8px 0;font-size:12px;line-height:1.55;color:var(--mut)}
.ev .src{display:block;font-size:10px;letter-spacing:.08em;text-transform:uppercase;color:var(--lab);margin-top:2px}
.banner{display:flex;gap:9px;align-items:center;border-top:1px solid var(--hair);border-bottom:1px solid var(--hair);
padding:10px 2px;font-size:12.5px;margin:12px 0 16px}
.banner b{font-weight:600}
.tweet{padding:9px 0;border-bottom:1px solid var(--hair);font-size:12.5px;line-height:1.55}
.tweet:last-child{border-bottom:none}
.tweet .m{font-size:10.5px;letter-spacing:.05em;color:var(--lab);margin-top:2px}
.tweet .m a{border-bottom:none}
.semi{font-size:12px;margin-right:5px}
.dhd{display:flex;align-items:baseline;gap:14px;flex-wrap:wrap;margin:2px 0 6px}
.dhd .nm{font-size:25px;font-weight:700;letter-spacing:-.02em}
.dhd .meta{font-size:11.5px;color:var(--mut)}
.backfoot{margin-top:22px;padding-top:12px;border-top:1px solid var(--hair);display:flex;gap:22px;font-size:12px;flex-wrap:wrap}
@media (prefers-reduced-motion: no-preference){ .lamp{animation:pulse 3.2s ease-in-out infinite}
@keyframes pulse{50%{opacity:.55}} }
</style></head><body><div class="wrap">
<div class="hdr"><h1>Brain<span class="dot">.</span></h1><span class="stamp">War Room · __STAMP__</span></div>
<div id="app"></div>
</div>
<script>const DATA=__DATA__;</script>
<script>
const LAMP={green:'#1F9D55',amber:'#F0A500',red:'#E30613',off:'#DDDDDD'};
const SEMI={bull:['🟢','bullish','#1F9D55'],bear:['🔴','bearish','#E30613'],injury:['🩹','injury','#F0A500'],
role:['🔀','role/scheme','#111111'],neutral:['·','neutral','#999999'],unlabeled:['·','unlabeled','#DDDDDD']};
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ol=(rel,label)=>`<a href="obsidian://open?vault=NFL-Brain&file=${encodeURIComponent(rel)}">${esc(label||rel.split('/').pop())}</a>`;
const lamp=(c,sm)=>`<span class="lamp${sm?' sm':''}" style="background:${LAMP[c]||c}"></span>`;
const fmt=(x,d=2)=>(x==null||x==='')?'–':(typeof x==='number'?x.toFixed(d):esc(x));
const pct=x=>x==null?'–':Math.round(x*100)+'%';
const plink=(k,n)=>DATA.players[k]?`<a href="#/player/${k}">${esc(n)}</a>`:esc(n);
const semIcon=s=>{const e=SEMI[s];return e&&e[0]!=='·'?`<span class="semi" title="${e[1]}">${e[0]}</span>`:`<span class="semi" style="color:#5C7089" title="${e?e[1]:'unlabeled'}">·</span>`};

function tabs(on){return `<div class="tabs"><a class="tab${on==='teams'?' on':''}" href="#/">Teams</a><a class="tab${on==='today'?' on':''}" href="#/today">Today</a></div>`}

/* ---------------- #/ teams grid ---------------- */
function vTeams(){
  const cards=Object.entries(DATA.teams).map(([ab,t])=>{
    const dcUnk=!!(t.cs26&&t.cs26.dcn&&t.cs26.conf==='regress-mean');
    const co=[['HC',t.hc,false,false],['OC',t.oc,!!(t.cc&&t.cc.oc_new),false],['DC',t.dc,!!(t.cc&&t.cc.dc_new),dcUnk]]
      .filter(r=>r[1]).map(r=>`${r[0]} <b>${esc(r[1])}</b>${r[2]?'<span class="new">NEW</span>':''}${r[3]?`<span title="new DC — coverage tendency unknown (regressed to league mean)" style="margin-left:4px">${lamp('amber',1)}</span>`:''}`).join(' · ');
    return `<a class="tcard" href="#/team/${ab}">
      <div class="tc-top"><span class="tc-ab">${ab}</span><span class="tc-nm">${esc(t.name)}</span><span class="tc-wt">${t.wt!=null?t.wt+'w':''}</span></div>
      <div class="tc-co">${co||'<span class="mut">no staff data</span>'}</div>
      <div class="tc-id">${esc(t.ident||t.outlook||'')}</div>
      <div class="tc-lamps">
        <span class="lamp-row">${lamp(t.schfl?'amber':'off',1)}<span>${t.schfl?`heavy ${t.proj&&t.proj.dir==='down'?'▼':'▲'} projected`:'personnel steady'}</span></span>
        <span class="lamp-row">${lamp(t.avct?'red':'off',1)}<span>${t.avct?t.avct+' availability flag'+(t.avct>1?'s':''):'no flags'}</span></span>
      </div></a>`;
  }).join('');
  return tabs('teams')+`<div class="cards">${cards}</div>`;
}

/* ---------------- #/today — v1 panels ---------------- */
function vToday(){
  const T=DATA.today;
  const rail=T.lamps.map(([c,t])=>`<div class="lamp-row">${lamp(c)}<span>${esc(t)}</span></div>`).join('');
  const threats=T.threats.map(e=>`<div class="row">${lamp(e.sev,1)}
    <span class="who">${plink(e.k,e.n)}</span><span class="what">${esc(e.term)}${e.x>1?' ×'+e.x:''}</span>
    <span class="when">${esc(String(e.d).slice(5))}</span></div>`).join('')||'<div class="mut">no availability flags — quiet room</div>';
  const mx=Math.max(1,...Object.values(T.radar));
  const radar=Object.entries(T.radar).filter(([k])=>SEMI[k]).sort((a,b)=>b[1]-a[1]).map(([k,v])=>
    `<div class="bar-row"><span class="bl">${SEMI[k][1]}</span><div class="bar"><i style="width:${(v/mx*100).toFixed(0)}%;background:${SEMI[k][2]}"></i></div><span class="bv">${v}</span></div>`
  ).join('')||'<div class="mut">no tweets yet today</div>';
  const ment=T.most.map(([m,k,c])=>`<span class="chip">${plink(k,m)} <b>${c}</b></span>`).join(' ')||'<span class="mut">—</span>';
  const theses=T.theses.map(([d,n,k,t])=>`<div class="thesis"><span class="when">${esc(String(d).slice(5))}</span> ${plink(k,n)} — ${esc(t)}</div>`).join('')||'<div class="mut">no new forward theses in 10 days</div>';
  const srcs=T.sources.map(s=>`<div class="row"><span class="who">${ol('Sources/'+s)}</span></div>`).join('')||'<div class="mut">—</div>';
  const rooms=T.rooms.map(([d,c,b])=>`<a class="room" href="obsidian://open?vault=NFL-Brain&file=${d}"><b>${d}</b><span class="rc">${c}</span><span class="rb">${esc(b)}</span></a>`).join('');
  const C=T.counts||{};
  return tabs('today')+`<div class="rail">${rail}</div><div class="grid">
    <div class="panel c6"><h2>Threat board — availability</h2>${threats}</div>
    <div class="panel c6"><div style="padding-bottom:14px"><h2>Discourse radar — today's ${T.n_tw} tweets</h2>${radar}</div>
      <h2>Most discussed today</h2><div>${ment}</div></div>
    <div class="panel c8"><h2>Fresh theses — forward signals, last 10 days</h2>${theses}</div>
    <div class="panel c4"><h2>Newest sources</h2>${srcs}</div>
    ${(()=>{const rows=(T.scheme_watch||[]).map(r=>{
        const d=(r[3]||0)-(r[2]||0);const ar=Math.abs(d)>=1.5?(d>0?' ▲':' ▼'):'';
        return `<tr><td><a href="#/team/${r[0]}">${r[0]}</a></td><td>${esc(r[1])}</td>
          <td class="num">${fmt(r[2],1)}% → <b>${fmt(r[3],1)}%</b>${ar}</td>
          <td class="num" style="color:${Math.abs(d)>=1.5?'var(--ink)':'var(--lab)'}">${(d>0?'+':'')+d.toFixed(1)}</td>
          <td>${r[4]==='blend-prior'?'<span class="chip">researched DC prior</span>':r[4]==='regress-mean'?'<span class="chip a">tendency unknown — regressed</span>':esc(r[4])}</td>
          <td class="num">${r[5]?`<a href="#/team/${r[0]}" title="coverage reports in the brain — open team room">${r[5]}</a>`:'<span style="color:var(--lab)">0</span>'}</td></tr>`}).join('');
      return rows?`<div class="panel c12"><h2>Scheme watch 2026 — new DCs, projected man-rate reprice (sorted by |Δ|)</h2>
        <div style="overflow-x:auto"><table class="tbl"><tr><th>team</th><th>new DC</th><th class="num">man 2025 → 2026 adj</th><th class="num">Δ</th><th>confidence</th><th class="num">intel</th></tr>${rows}</table></div></div>`:'';})()}
    <div class="panel c12"><h2>Rooms</h2><div class="rooms">${rooms}</div></div></div>
  <div class="foot"><span>knowledge base: ${C.players??'?'} players · ${C.teams??'?'} teams · ${C.coaches??'?'} coaches · ${C.tweets_scanned??'?'} tweets scanned · ${C.claims_seen??'?'} claims</span>
  <span>${T.n_sig_players} players carry film signal</span><span>export ${esc(T.intel_gen)}</span></div>`;
}

/* ---------------- #/team/<ABBR> ---------------- */
function vTeam(ab){
  const t=DATA.teams[ab];
  if(!t) return tabs('teams')+`<div class="panel"><div class="mut">unknown team “${esc(ab)}” — <a href="#/">back to the grid</a></div></div>`;
  const cc=t.cc||{};
  const ccBits=[];
  if(cc.oc_new) ccBits.push(`<span class="badge amber">NEW OC</span> <b>${esc(cc.oc_name||t.oc)}</b>`);
  if(cc.dc_new) ccBits.push(`<span class="badge amber">NEW DC</span> <b>${esc(cc.dc_name||t.dc)}</b>${cc.dc_scheme?' — '+esc(cc.dc_scheme):''}${cc.def_caller?' · calls: '+esc(cc.def_caller):''}`);
  const ccSrc=cc.source||cc.dc_source||cc.src;
  const identity=`
    <div class="note">${t.ident?`<b>Identity:</b> ${esc(t.ident)}<br>`:''}
    ${t.outlook?`<b>2026:</b> ${esc(t.outlook)}<br>`:''}
    ${t.snote?`<b>Scheme:</b> ${esc(t.snote)}<br>`:''}
    ${t.pc?`<b>Play-caller:</b> ${esc(t.pc)}<br>`:''}
    ${t.defc?`<b>Defense:</b> ${esc(t.defc)}<br>`:''}
    ${t.dnote?`<b>Def scheme:</b> ${esc(t.dnote)}<br>`:''}
    ${ccBits.length?`<div style="margin-top:7px">${ccBits.join('<br>')}${ccSrc?`<span class="ev src" style="border:none;padding:0">source: ${esc(ccSrc)} (verified registry)</span>`:''}</div>`:'<span class="mut">no 2026 coordinator change on record</span>'}</div>`;
  const moves=`<div class="grid" style="gap:10px">
    <div class="c6"><h2 style="margin-bottom:6px">Key additions</h2>${(t.adds.length?t.adds.map(a=>`<div class="row"><span class="who">＋ ${esc(a)}</span></div>`).join(''):'<div class="mut">none recorded</div>')}</div>
    <div class="c6"><h2 style="margin-bottom:6px">Key losses</h2>${(t.losses.length?t.losses.map(a=>`<div class="row"><span class="who">－ ${esc(a)}</span></div>`).join(''):'<div class="mut">none recorded</div>')}</div></div>`;
  const P=t.pers||{}, mix=P.mix||{};
  const mixChips=Object.entries(mix).sort((a,b)=>b[1]-a[1]).map(([g,v])=>`<span class="chip">${g} <b>${pct(v)}</b></span>`).join('');
  const pj=t.proj;
  const dirBadge=d=>d==='up'?'<span class="badge green">HEAVY ▲</span>':d==='down'?'<span class="badge red">HEAVY ▼</span>':d?`<span class="badge blue">${esc(d)}</span>`:'<span class="badge blue">steady</span>';
  const projHtml=pj?`<div class="note" style="margin-top:10px">
      ${dirBadge(pj.dir)} ${pj.emph&&pj.emph.length?`emphasis: <b>${pj.emph.map(esc).join(', ')}</b> · `:''}${pj.oc26?`<span class="mut">${esc(pj.oc26)}</span>`:''}
      <div style="margin-top:6px"><b>Rationale:</b> ${esc(pj.why||'—')}</div>
      ${pj.base&&pj.base.heavy_rate!=null?`<div class="mut" style="margin-top:4px">2025 baseline: heavy ${pj.base.heavy_rate}% (rank ${esc(String(pj.base.heavy_rank??'–'))}) · ${(pj.base.top_groupings||[]).map(esc).join(' · ')}</div>`:''}
      ${(pj.ev||[]).map(e=>`<div class="ev">${esc(e.c)}<span class="src">${esc(e.s)}</span></div>`).join('')}</div>`
    :'<div class="mut" style="margin-top:8px">no 2026 personnel projection on file</div>';
  const fppRows=t.fpp.map(r=>`<tr><td>${r.k?`<a href="#/player/${r.k}">${esc(r.n)}</a>`:esc(r.n)}</td><td>${esc(r.pos)}</td>
    <td class="num">${r.routes??'–'}</td><td class="num">${pct(r.hs)}</td>
    <td class="num">${fmt(r.t11)}</td><td class="num">${fmt(r.d11)}</td>
    <td class="num">${fmt(r.th)}</td><td class="num">${fmt(r.dh)}</td></tr>`).join('');
  const personnel=`<div class="kv">
      <span><span class="k">heavy 2025</span><span class="v">${fmt(P.heavy,1)}%<small> rk ${P.rank??'–'}</small></span></span>
      <span><span class="k">FP heavy</span><span class="v">${fmt(P.fph,1)}%</span></span>
      <span><span class="k">play-action</span><span class="v">${fmt(P.pa,1)}%</span></span>
      <span><span class="k">motion</span><span class="v">${fmt(P.motion,1)}%</span></span>
      <span><span class="k">pace pctl</span><span class="v">${fmt(P.pace,0)}</span></span></div>
    <div>${mixChips}</div>${projHtml}
    ${t.fpp.length?`<div style="margin-top:12px;overflow-x:auto"><table class="tbl"><tr><th>player (routes ≥150)</th><th>pos</th><th class="num">routes</th><th class="num">%heavy</th><th class="num">TPRR 11</th><th class="num">DK/RR 11</th><th class="num">TPRR hvy</th><th class="num">DK/RR hvy</th></tr>${fppRows}</table></div>`:'<div class="mut" style="margin-top:8px">no FP personnel splits (routes ≥150) for this roster</div>'}`;
  const dp=t.dp||{}, sh=(t.sp||{}).shell||{}, bp=(t.sp||{}).bypos||{};
  const soft=Object.entries(bp).filter(([,v])=>v>=3).sort((a,b)=>b[1]-a[1]);
  const sting=Object.entries(bp).filter(([,v])=>v<=-3).sort((a,b)=>a[1]-b[1]);
  const shellBar=(l,v,c)=>v==null?'':`<div class="bar-row"><span class="bl">${l}</span><div class="bar"><i style="width:${Math.min(100,v).toFixed(0)}%;background:${c}"></i></div><span class="bv">${v.toFixed(0)}%</span></div>`;
  const ngsRows=Object.entries(t.ngs||{}).map(([k,v])=>`<tr><td>${esc(k)}</td>
    <td class="num">${v.soft??'–'}</td><td class="num">${v.sep??'–'}</td><td class="num">${fmt(v.epa,3)}</td></tr>`).join('');
  const dfns=`<div class="note">
      <b>Attack via:</b> ${dp.atk&&dp.atk.length?dp.atk.map(x=>`<span class="chip g">${esc(x)} <b>+${fmt(dp.fpaa[x.toLowerCase()],1)}</b></span>`).join(''):'<span class="mut">no clear soft lane</span>'}
      ${dp.avd&&dp.avd.length?`<br><b>Avoid:</b> ${dp.avd.map(x=>`<span class="chip r">${esc(x)} <b>${fmt(dp.fpaa[x.toLowerCase()],1)}</b></span>`).join('')}`:''}
      ${dp.lean?`<div style="margin-top:6px"><b>2026 engine lean:</b> ${esc(dp.lean)}-funnel</div>`:''}
      ${dp.cb1&&dp.cb1.name?`<div class="mut" style="margin-top:3px">CB1 ${esc(dp.cb1.name)} · cov ${fmt(dp.cb1.cov,1)} · ${esc(dp.cb1.tier||'')}</div>`:''}
      ${(dp.fun||[]).map(f=>`<div class="thesis">${esc(f)}</div>`).join('')}</div>
    ${(()=>{const c=t.cs26;if(!c)return '';
      if(!c.dcn)return `<div class="sublab">2026 scheme continuity</div><div class="mut" style="font-size:11.5px">DC returns — 2025 shell stands</div>`;
      const d=(c.ma!=null&&c.m25!=null)?c.ma-c.m25:null;
      const ar=d!=null&&Math.abs(d)>=1.5?(d>0?' ▲':' ▼'):'';
      const chip=c.conf==='blend-prior'?'<span class="chip">researched DC prior</span>'
        :c.conf==='regress-mean'?`<span class="chip a">tendency unknown — regressed toward league ${DATA.meta.man_mean??17.5}%</span>`:'';
      const di=t.dci;
      const heard=di&&di.items&&di.items.length
        ?di.items.map(q=>`<div class="thesis"><span class="when">${esc(String(q.d).slice(5))}</span> ${esc(q.t)} <span class="mut" style="font-size:10.5px">— ${esc(q.a)}</span></div>`).join('')
        :'<div class="mut" style="font-size:11.5px">no coverage reports captured yet — watching.</div>';
      return `<div class="sublab">2026 scheme continuity</div>
        <div class="note"><span class="badge red">NEW DC</span> <b>${esc(c.dc||'?')}</b>: man ${fmt(c.m25,1)}% → <b>${fmt(c.ma,1)}%${ar}</b> · blitz-sack ${fmt(c.s25,1)}% → ${fmt(c.sa,1)}% ${chip}</div>
        <div class="sublab">What the brain has heard</div>${heard}`;})()}
    <div class="sublab">2025 measured shell — last year's rates, not the 2026 projection above</div>
    <div>${shellBar('man',sh.man_rate,'#E30613')}${shellBar('single-high',sh.single_high,'#111')}${shellBar('two-high',sh.two_high,'#111')}</div>
    ${soft.length||sting.length?`<div style="margin-top:8px">${soft.map(([k,v])=>`<span class="chip g">soft vs ${k.toUpperCase()} <b>+${v.toFixed(1)}</b></span>`).join('')}${sting.map(([k,v])=>`<span class="chip r">stingy vs ${k.toUpperCase()} <b>${v.toFixed(1)}</b></span>`).join('')}</div>`:''}
    ${(()=>{const VS=(t.sp||{}).vs||{};
      const vb=(l,o)=>o&&o.soft!=null?`<div class="bar-row"><span class="bl">${l}</span><div class="bar"><i style="width:${Math.min(100,o.soft).toFixed(0)}%;background:#E30613"></i></div><span class="bv">${o.soft.toFixed(0)}</span><span class="bx">${o.ypr!=null?o.ypr.toFixed(2)+' ypr':''}</span></div>`:'';
      const rows=['man','zone','deep','short'].map(k=>vb('vs '+k,VS[k])).join('');
      return rows?`<div class="sublab">Coverage splits — high pctl = soft / attackable, low = stingy</div>${rows}`:'';})()}
    ${(()=>{const U=(t.sp||{}).units||{};
      const ub=(l,v)=>v!=null?`<div class="bar-row"><span class="bl">${l}</span><div class="bar"><i style="width:${Math.min(100,v).toFixed(0)}%;background:#111"></i></div><span class="bv">${v.toFixed(0)}</span></div>`:'';
      const rows=ub('pass cov',U.pass_cov_pctl)+ub('pass rush',U.pass_rush_pctl)+ub('run def',U.run_def_pctl);
      return rows?`<div class="sublab">Unit strength — pctl, high = good unit</div>${rows}`:'';})()}
    ${ngsRows?`<div style="margin-top:12px;overflow-x:auto"><table class="tbl"><tr><th>NGS lane (2025)</th><th class="num">soft pctl</th><th class="num">sep pctl</th><th class="num">EPA/pass</th></tr>${ngsRows}</table></div>`:''}`;
  const E=t.env||{};
  const envHtml=`<div class="kv">
      <span><span class="k">ceiling score</span><span class="v">${fmt(E.ceil,1)}<small> ${esc(E.tier||'')} · rk ${E.rank??'–'}</small></span></span>
      <span><span class="k">PROE 2026</span><span class="v">${E.proe!=null?(E.proe>0?'+':'')+E.proe.toFixed(1):'–'}<small> 2025 ${E.proe25!=null?(E.proe25>0?'+':'')+E.proe25.toFixed(1):'–'}</small></span></span>
      <span><span class="k">underdog</span><span class="v">${E.dogs??'–'}/${E.gms??'–'}<small> simmed games</small></span></span>
      <span><span class="k">avg implied</span><span class="v">${fmt(E.imp,1)}<small> pts</small></span></span></div>
    ${E.drv&&E.drv.length?`<div class="mut" style="font-size:12px">top drivers: ${E.drv.map(([k,v])=>`${esc(k)} ${v.toFixed(2)}`).join(' · ')}</div>`:''}
    ${E.flags&&E.flags.length?`<div style="margin-top:4px">${E.flags.map(f=>`<span class="chip">${esc(f)}</span>`).join('')}</div>`:''}
    ${E.pnote?`<div class="mut" style="margin-top:6px;font-size:11.5px">${esc(E.pnote)}</div>`:''}`;
  const rosterRows=t.roster.map(([k,n,pos,adp,av,sig,noi])=>{
    const pa=(DATA.players[k]||{}).av;
    const sev=pa&&/acl|achilles|fractur|surger/.test(String(pa.term||''))?'red':'amber';
    return `<tr>
    <td><a href="#/player/${k}">${esc(n)}</a></td><td>${esc(pos)}</td>
    <td class="num">${adp!=null?adp.toFixed(1):'–'}</td>
    <td>${av?`<span class="lamp-row" style="display:inline-flex">${lamp(sev,1)}<span class="what">${esc(pa&&pa.term||'flag')}</span></span>`:''}</td>
    <td class="num">${sig||''}</td><td class="num" style="color:var(--lab)">${noi||''}</td></tr>`}).join('');
  const co=[['HC',t.hc,false],['OC',t.oc,!!cc.oc_new],['DC',t.dc,!!cc.dc_new]].filter(r=>r[1])
    .map(r=>`${r[0]} <b>${esc(r[1])}</b>${r[2]?'<span class="new">NEW</span>':''}`).join(' · ');
  return tabs('teams')+`<div class="crumb"><a href="#/">TEAMS</a> / ${ab}</div>
    <div class="dhd"><span class="nm">${esc(t.name)}</span><span class="meta">${t.wt!=null?'win total '+t.wt:''}</span></div>
    <div class="tc-co" style="font-size:12px;margin:0 0 16px">${co}</div>
    <div class="grid">
      <div class="panel c6 sect"><h2>1 · Identity &amp; scheme</h2>${identity}</div>
      <div class="panel c6 sect"><h2>2 · Roster changes</h2>${moves}</div>
      <div class="panel c12 sect"><h2>3 · Personnel — 2025 mix &amp; 2026 projection</h2>${personnel}</div>
      <div class="panel c6 sect"><h2>4 · Defensive identity</h2>${dfns}</div>
      <div class="panel c6 sect"><h2>5 · Environment</h2>${envHtml}</div>
      <div class="panel c12 sect"><h2>6 · Roster — by ADP</h2>
        ${t.roster.length?`<div style="overflow-x:auto"><table class="tbl"><tr><th>player</th><th>pos</th><th class="num">ADP</th><th>avail</th><th class="num">sig</th><th class="num">noise</th></tr>${rosterRows}</table></div>`:'<div class="mut">no rostered players in statmenu</div>'}</div>
    </div>
    <div class="backfoot">${ol('Concepts/'+t.name,'⧉ concept page in Obsidian')}${ol('Teams/'+t.name,'⧉ team entity')}<a href="#/">← all teams</a></div>`;
}

/* ---------------- #/player/<slug> ---------------- */
function vPlayer(k){
  const p=DATA.players[k];
  if(!p) return tabs('teams')+`<div class="panel"><div class="mut">unknown player “${esc(k)}” — <a href="#/">back to the grid</a></div></div>`;
  const q=p.q||{}, fus=q.fus||{}, use=q.use||{}, adot=q.adot||{}, rz=q.rz||{}, env=q.env||{}, sc=p.sched||{};
  const avSev=p.av&&/acl|achilles|fractur|surger/.test(String(p.av.term||''))?'red':'amber';
  const banner=p.av?`<div class="banner">${lamp(avSev,1)}<span><b>availability flag:</b> “${esc(p.av.term)}”${p.av.n>1?' ×'+p.av.n:''} · last seen ${esc(p.av.d||'')}</span></div>`:'';
  const facts=[];
  if(p.cs&&p.cs.best) facts.push(`<span><span class="k">best coverage</span><span class="v" style="font-size:12.5px">${esc(p.cs.best)}<small> ${p.cs.pctl!=null?p.cs.pctl+'th pctl':''}</small></span></span>`);
  if(p.fun&&p.fun.wf) facts.push(`<span><span class="k">wins from</span><span class="v" style="font-size:12.5px">${esc(p.fun.wf)}<small> home: ${esc(p.fun.home||'–')}</small></span></span>`);
  if(sc.bye!=null) facts.push(`<span><span class="k">bye</span><span class="v">W${sc.bye}</span></span>`);
  if(sc.w15) facts.push(`<span><span class="k">W15 · W16 · W17</span><span class="v" style="font-size:12.5px">${esc(sc.w15)} · ${esc(sc.w16||'–')} · ${esc(sc.w17||'–')}</span></span>`);
  const fusChips=Object.entries(fus).map(([kk,v])=>`<span class="chip">${esc(kk.replace('_pctl',''))} <b>${Math.round(v)}</b></span>`).join('');
  const quant=`<div class="kv">
      <span><span class="k">boom blended</span><span class="v">${fmt(q.bb,3)}<small> base ${fmt(q.boom,3)} · ${q.ng??'–'}g/${q.bg??'–'}boom</small></span></span>
      ${adot.TPRR!=null?`<span><span class="k">TPRR</span><span class="v">${fmt(adot.TPRR,3)}<small> +${fmt(adot.surplus_TPRR,3)} surplus</small></span></span>`:''}
      ${adot.aDOT!=null?`<span><span class="k">aDOT</span><span class="v">${fmt(adot.aDOT,1)}</span></span>`:''}
      ${use.tgt_share!=null?`<span><span class="k">tgt share</span><span class="v">${pct(use.tgt_share)}</span></span>`:''}
      ${use.carry_share!=null&&use.carry_share>0.03?`<span><span class="k">carry share</span><span class="v">${pct(use.carry_share)}<small> ${fmt(use.ypc,2)} ypc</small></span></span>`:''}
      ${use.dk_pg!=null?`<span><span class="k">DK/gm</span><span class="v">${fmt(use.dk_pg,1)}</span></span>`:''}
      ${rz.rz_tgt_share!=null?`<span><span class="k">RZ/EZ tgt</span><span class="v">${rz.rz_tgt_share}%/${rz.ez_tgt_share??'–'}%<small> ${rz.ez_td??0} EZ TD</small></span></span>`:''}
      ${env.env_idx!=null?`<span><span class="k">team env</span><span class="v">${env.env_idx}<small> pace ${env.pace_pctl??'–'} · ${env.win_total??'–'}w</small></span></span>`:''}
    </div>${fusChips?`<div style="margin-top:6px">${fusChips}</div>`:'<div class="mut">no FUS percentiles</div>'}`;
  let coverage='';
  {
    const elp=DATA.meta.el_p??85, wkp=DATA.meta.wk_p??20;
    let fitBlock='', buckets='', chips='', schTable='';
    if(p.cov){
      const c=p.cov;
      const bb=(l,o)=>o&&o.p!=null?`<div class="bar-row"><span class="bl">${l}</span><div class="bar"><i style="width:${Math.min(100,o.p).toFixed(0)}%;background:#111"></i></div><span class="bv">${o.p.toFixed(0)}</span><span class="bx">${o.r!=null?o.r+' rte':''}</span></div>`:'';
      buckets=[['man','man'],['zone','zone'],['single-high','single_high'],['two-high','two_high']].map(([l,kk])=>bb(l,c.b[kk])).join('');
      const cell=e=>`${esc(e.k)} <b>${e.p!=null?Math.round(e.p):'–'}</b> · ${e.y!=null?e.y.toFixed(2):'–'} yprr · ${e.r??'–'} rte`;
      const el=(c.el||[]).map(e=>`<span class="chip g">${cell(e)}</span>`).join('');
      const wkc=(c.wk||[]).map(e=>`<span class="chip r">${cell(e)}</span>`).join('');
      chips=`${el?`<div class="sublab">Elite vs</div><div>${el}</div>`:''}
        ${wkc?`<div class="sublab">Weak vs</div><div>${wkc}</div>`:''}
        ${(el||wkc)?'<div class="mut" style="font-size:11px;margin-top:6px">extremes only — the mid-tier schemes are uncharted for this player</div>':''}`;
      const f=c.fit||{};
      const sf=x=>x==null?'–':(x>0?'+':'')+x.toFixed(3);
      const fc=x=>x==null?'var(--lab)':x>0?'var(--green)':x<0?'var(--red)':'var(--ink)';
      const pwRows=(c.pw||[]).map(w=>`<tr><td class="num">W${w.wk}</td><td>${esc(w.opp)}${w.nd?' <span class="badge red">new DC</span>':''}${w.ma!=null?` <span style="font-size:10.5px;color:var(--lab)">man ${w.ma}% (${esc(w.cf||'')})</span>`:''}</td><td class="num" style="color:${fc(w.fit)};font-weight:600">${sf(w.fit)}</td><td style="color:var(--mut)">${esc(w.why)}</td></tr>`).join('');
      fitBlock=`
        <div class="sublab">2026 playoff coverage fit — + = opponent coverage tendencies meet his strengths, − = they lean away from them</div>
        <div class="kv" style="margin-bottom:8px">
          <span><span class="k">playoff W15-17</span><span class="v" style="color:${fc(f.p)}">${sf(f.p)}</span></span>
          <span><span class="k">regular</span><span class="v" style="color:${fc(f.r)}">${sf(f.r)}</span></span>
          <span><span class="k">season</span><span class="v" style="color:${fc(f.s)}">${sf(f.s)}</span></span></div>
        ${pwRows?`<div style="overflow-x:auto"><table class="tbl"><tr><th class="num">wk</th><th>opp</th><th class="num">fit</th><th>why</th></tr>${pwRows}</table></div>`:''}`;
    }
    if(p.sch&&p.sch.length){
      const hasAdv=p.sch.some(r=>r.a);
      const mzLine=p.mz?`<div class="note" style="margin:0 0 8px;font-size:12px">
        <b>Man/Zone outcome split:</b> EPA/tgt <b>${p.mz.m!=null?p.mz.m.toFixed(2):'–'}</b> man vs <b>${p.mz.z!=null?p.mz.z.toFixed(2):'–'}</b> zone
        (Δ${p.mz.d!=null?(p.mz.d>0?'+':'')+p.mz.d.toFixed(2):'–'}) · <b>${p.mz.sh!=null?p.mz.sh.toFixed(1):'–'}%</b> routes vs man</div>`:'';
      const advHd=hasAdv?`<th class="num">TPRR</th><th class="num">sepW%</th><th class="num">aDOT</th><th class="num">ctc%</th><th class="num">DK/rt</th>`:'';
      const rows=p.sch.map(r=>{
        const rated=r.p!=null&&r.q;
        const tint=rated?(r.p>=elp?'background:rgba(31,157,85,.06)':r.p<=wkp?'background:rgba(227,6,19,.05)':''):'';
        const col=rated?(r.p>=elp?'var(--green)':r.p<=wkp?'var(--red)':'var(--ink)'):'var(--lab)';
        const bar=r.p!=null?`<div style="display:flex;align-items:center;gap:8px"><div class="bar" style="width:120px;flex:none"><i style="width:${Math.min(100,r.p).toFixed(0)}%;background:${rated?(r.p>=elp?'#1F9D55':r.p<=wkp?'#E30613':'#111'):'#DDD'}"></i></div><b style="color:${col}">${Math.round(r.p)}</b>${r.q?'':' <span class="mut" style="font-size:10px">low n</span>'}</div>`:'<span class="mut" style="font-size:11px">low n — unranked</span>';
        const a=r.a||{};
        const advTd=hasAdv?`<td class="num">${a.t!=null?a.t.toFixed(2):'–'}</td>
          <td class="num">${a.sw!=null?Math.round(a.sw*100)+'%':'–'}</td>
          <td class="num">${a.ad!=null?a.ad.toFixed(1):'–'}</td>
          <td class="num">${a.cc!=null?Math.round(a.cc*100)+'%':'–'}</td>
          <td class="num">${a.dk!=null?a.dk.toFixed(2):'–'}</td>`:'';
        return `<tr style="${tint}"><td>${esc(r.k)}</td><td class="num">${r.rte??'–'}</td><td class="num">${r.y!=null?r.y.toFixed(2):'–'}</td><td>${bar}</td>${advTd}</tr>`}).join('');
      schTable=mzLine+`<div class="sublab">Full per-scheme spec — routes/yprr/pctl are 2yr${hasAdv?'; TPRR·sepW%·aDOT·ctc%·DK/rt are 2025 DK vintage (sepW% charted for C2/C3/C4/C6 only)':''} — sorted by exposure (green ≥${elp}th · red ≤${wkp}th pctl)</div>
        <div style="overflow-x:auto"><table class="tbl"><tr><th>scheme</th><th class="num">routes</th><th class="num">yprr</th><th>pctl</th>${advHd}</tr>${rows}</table></div>`;
    }
    if(fitBlock||schTable||buckets){
      coverage=fitBlock
        +(buckets?`<div class="sublab">Coverage buckets — production pctl vs each look</div>${buckets}`:'')
        +(schTable||chips);
    } else if(p.cs&&p.cs.pctls){
      const bb=(l,v)=>v!=null?`<div class="bar-row"><span class="bl">${l}</span><div class="bar"><i style="width:${Math.min(100,v).toFixed(0)}%;background:#111"></i></div><span class="bv">${Math.round(v)}</span></div>`:'';
      const rows=[['man','man'],['zone','zone'],['single-high','single_high'],['two-high','two_high']].map(([l,kk])=>bb(l,p.cs.pctls[kk])).join('');
      coverage=rows?`<div class="sublab">Coverage-spec percentiles — statmenu fallback (player not in the scheme-fit engine)</div>${rows}`:'';
    }
    if(!coverage){
      coverage=(p.pos==='RB'||p.pos==='QB')
        ?`<div class="mut">No coverage spec — position not charted (${esc(p.pos)})</div>`
        :'<div class="mut">No coverage charting for this player — routes below spec minimums</div>';
    }
  }
  let funnels='<div class="mut">no 2025 route/funnel data</div>';
  if(p.fun&&(p.fun.recv||p.fun.mix)){
    const r=p.fun.recv||{};
    const mixChips=Object.entries(p.fun.mix||{}).sort((a,b)=>b[1]-a[1]).map(([g,v])=>{
      const y=(p.fun.yprr_by||{})[g], s=(p.fun.sep_by||{})[g];
      return `<span class="chip">${g} <b>${pct(v)}</b>${y!=null?` · ${y.toFixed(2)} yprr`:''}${s!=null?` · ${s.toFixed(2)} sep`:''}</span>`}).join('');
    funnels=`<div class="kv">
      ${r.yprr!=null?`<span><span class="k">YPRR</span><span class="v">${fmt(r.yprr,2)}</span></span>`:''}
      ${r.croe!=null?`<span><span class="k">CROE</span><span class="v">${fmt(r.croe,2)}</span></span>`:''}
      ${r.avg_sep!=null?`<span><span class="k">avg sep</span><span class="v">${fmt(r.avg_sep,2)}</span></span>`:''}
      ${r.routes!=null?`<span><span class="k">routes</span><span class="v">${r.routes}<small> ${fmt(r.routes_pg,1)}/gm</small></span></span>`:''}
      ${r.rec_epa!=null?`<span><span class="k">rec EPA</span><span class="v">${fmt(r.rec_epa,1)}</span></span>`:''}</div>
      ${mixChips?`<div style="margin-top:4px">${mixChips}</div>`:''}`;
    if(p.fun.rush){const u=p.fun.rush;
      funnels+=`<div class="kv" style="margin-top:8px">
        <span><span class="k">rush att</span><span class="v">${u.att??'–'}<small> ${fmt(u.att_pg,1)}/gm</small></span></span>
        <span><span class="k">ypc</span><span class="v">${fmt(u.ypc,2)}</span></span>
        <span><span class="k">RYOE/att</span><span class="v">${fmt(u.ryoe_att,2)}</span></span>
        <span><span class="k">YAC/att</span><span class="v">${fmt(u.yaco_att,2)}</span></span></div>`;}
  }
  let fpHtml='<div class="mut">no FP personnel split (needs routes in the FP sweep)</div>';
  if(p.fp){const f=p.fp;
    const mixChips=Object.entries(f.mix||{}).sort((a,b)=>b[1]-a[1]).map(([g,v])=>`<span class="chip">${g} <b>${pct(v)}</b></span>`).join('');
    fpHtml=`<div>${mixChips} <span class="chip">heavy <b>${pct(f.hs)}</b></span></div>
      <div class="kv" style="margin-top:8px">
        <span><span class="k">TPRR 11 / heavy</span><span class="v">${fmt(f.t11)} / ${fmt(f.th)}</span></span>
        <span><span class="k">DK/RR 11 / heavy</span><span class="v">${fmt(f.d11)} / ${fmt(f.dh)}</span></span>
        <span><span class="k">routes</span><span class="v">${f.routes??'–'}</span></span></div>
      ${f.th!=null&&f.d11!=null&&f.dh!=null?`<div class="mut" style="font-size:12px;margin-top:4px">${f.dh>f.d11?'MORE productive per route from heavy personnel — a heavy-shift offense raises his floor.':'more productive per route from 11 personnel.'}</div>`:''}`;}
  const tweets=(p.tw||[]).map(t=>`<div class="tweet">${semIcon(t.s)}${esc(t.t)}
      <div class="m">${esc(t.a)} · ${esc(t.d)}${t.u?` · <a href="${esc(t.u)}" target="_blank" rel="noopener">↗</a>`:''}</div></div>`).join('')
    ||'<div class="mut">no tweets captured for this player</div>';
  const fwd=(p.fwd||[]).map(f=>`<div class="thesis"><span class="when">${esc(String(f.d).slice(5))}</span> <span class="what">${esc(f.s)}</span> ${esc(f.t)}</div>`).join('')
    ||'<div class="mut">no forward claims</div>';
  return tabs('teams')+`<div class="crumb"><a href="#/">TEAMS</a> / <a href="#/team/${esc(p.tm)}">${esc(p.tm)}</a> / ${esc(p.n).toUpperCase()}</div>
    <div class="dhd"><span class="nm">${esc(p.n)}</span><span class="meta">${esc(p.pos)} · <a href="#/team/${esc(p.tm)}">${esc(p.tm)}</a> · ADP ${p.adp!=null?p.adp.toFixed(1):'–'} (as of ${esc(DATA.meta.adp_asof||'?')})${p.sig?` · ${p.sig} signal notes`:''}</span></div>
    ${banner}
    <div class="grid">
      <div class="panel c12 sect"><h2>Facts</h2><div class="kv">${facts.join('')||'<span class="mut">—</span>'}</div></div>
      <div class="panel c12 sect"><h2>Coverage — 2026 scheme fit</h2>${coverage}</div>
      <div class="panel c12 sect"><h2>Quant strip — blended model</h2>${quant}</div>
      <div class="panel c6 sect"><h2>Funnels — 2025 route &amp; alignment</h2>${funnels}</div>
      <div class="panel c6 sect"><h2>Personnel reliance — 11 vs heavy</h2>${fpHtml}</div>
      <div class="panel c6 sect"><h2>Intel — newest tweets</h2>${tweets}</div>
      <div class="panel c6 sect"><h2>Forward claims</h2>${fwd}</div>
    </div>
    <div class="backfoot">${ol('Players/'+p.os,'⧉ full dossier in Obsidian')}<a href="#/team/${esc(p.tm)}">← ${esc(p.tm)} team room</a><a href="#/">← all teams</a></div>`;
}

/* ---------------- router ---------------- */
function route(){
  const h=location.hash||'#/';
  const app=document.getElementById('app');
  let m;
  if((m=h.match(/^#\/team\/([A-Z]{2,3})/))) app.innerHTML=vTeam(m[1]);
  else if((m=h.match(/^#\/player\/([a-z0-9-]+)/))) app.innerHTML=vPlayer(m[1]);
  else if(h.startsWith('#/today')) app.innerHTML=vToday();
  else app.innerHTML=vTeams();
  window.scrollTo(0,0);
}
window.addEventListener('hashchange',route);
route();
</script></body></html>"""

# ---------------------------------------------------------------- main
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--vault", required=True); ap.add_argument("--repo", default=None)
    a = ap.parse_args()
    vault = os.path.expanduser(a.vault); repo = bc.repo_root(a.repo)
    now = datetime.now()

    sm = jload(repo, "boom", "statmenu.json") or {}
    sm = {k: v for k, v in sm.items() if not k.startswith("_") or k == "_refresh"}
    bi = jload(repo, "brain_intel.json") or {}
    sem = jload(HERE, "tweet_semantics.json") or {}
    intel = {fn(k): v for k, v in (bi.get("players") or {}).items()}
    pfun = (jload(repo, "player_funnels.json") or {}).get("players", {})
    fp = jload(repo, "fp_personnel.json") or {}
    sfit = (jload(repo, "boom", "scheme_fit.json") or {}).get("players", {})
    csch = jload(repo, "coordinator_scheme_2026.json") or {}
    cs26 = csch.get("teams", {})
    cs26_meta = csch.get("meta", {})
    crs = jload(repo, "boom", "coverage_route_spec.json") or {}
    crsp = {p.get("key"): p for p in (crs.get("players") or []) if isinstance(p, dict) and p.get("key")}
    # man/zone EPA-per-target + man-route exposure from the DFS source-fusion drivers
    dfs_drv = {fn(p.get("name", "")): (p.get("drivers") or {})
               for p in (jload(repo, "dfs_scenarios.json") or {}).get("players", [])
               if isinstance(p, dict) and p.get("name")}
    off = jload(repo, "offense_profile.json") or {}
    sch = {k: v for k, v in (jload(repo, "scheme_2026.json") or {}).items() if k != "_meta"}
    cc = {k: v for k, v in (jload(repo, "coordinator_changes_2026.json") or {}).items() if not k.startswith("_")}
    wt = {t.get("team"): t for t in (jload(repo, "web_teams.json") or []) if isinstance(t, dict)}
    pers = (jload(repo, "personnel_2026.json") or {}).get("teams", {})
    _pp = jload(repo, "personnel_2026_projection.json") or {}
    proj = {k: v for k, v in _pp.items() if not k.startswith("_")}
    dprof = jload(repo, "boom", "defensive_profile.json") or {}
    ds = {k: v for k, v in (jload(repo, "defense_splits.json") or {}).items() if not k.startswith("_")}
    ngs = (jload(repo, "nflpro_2025.json") or {}).get("teams", {})
    tc = (jload(repo, "team_ceiling.json") or {}).get("teams", {})
    proe = (jload(repo, "proe_tendency_2026.json") or {}).get("teams", {})
    genv = _game_env(jload(repo, "game_sim.json") or {})

    smp = {k: v for k, v in sm.items() if isinstance(v, dict) and v.get("name")}
    dci = build_dc_intel(cs26, bi)
    players = build_players(smp, intel, sem, pfun, fp.get("players", {}), sfit, cs26, crsp, dfs_drv)
    teams = build_teams(smp, players, off, sch, cc, wt, pers, proj, fp.get("players", {}),
                        dprof, ds, ngs, tc, proe, genv, cs26, dci)
    today = build_today(vault, repo, smp, bi, sem, cs26, dci)

    data = {"meta": {"generated": now.strftime("%Y-%m-%d %H:%M"),
                     "adp_asof": ((sm.get("_refresh") or {}).get("adp_asof", "")),
                     "man_mean": cs26_meta.get("man_league_mean"),
                     "el_p": crs.get("elite_pctl", 85), "wk_p": crs.get("weak_pctl", 20),
                     "n_players": len(players), "n_teams": len(teams)},
            "today": today, "teams": teams, "players": players}

    payload = json.dumps(data, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")
    page = (HTML.replace("__STAMP__", html.escape(now.strftime("%a %Y-%m-%d %H:%M").upper()))
                .replace("__DATA__", payload))
    out = os.path.join(vault, "warroom.html")
    open(out, "w", encoding="utf-8").write(page)
    kb = os.path.getsize(out) // 1024
    bc.log(f"warroom v2: {out} — {len(teams)} teams · {len(players)} players · "
           f"{len(today['threats'])} threats · {today['n_tw']} tweets today · {kb} KB")
    print(json.dumps({"teams": len(teams), "players": len(players),
                      "threats": len(today["threats"]), "tweets_today": today["n_tw"],
                      "theses": len(today["theses"]), "kb": kb}))
    return 0

if __name__ == "__main__":
    sys.exit(main())
