#!/usr/bin/env python3
"""build_coaching_brief.py — regenerate COACHING_CHANGES_2026_DETAIL.md from LIVE model data.

Replaces the stale hand-built brief (which listed OC titles that aren't the play-caller, omitted
CAR, and contradicted offense_profile on LV). Single source of truth: offense_profile.json
(playcaller-first identities + numeric PA%/motion%/pace/zone-rate) + proe_tendency_2026.json +
dossier_data.json (top-5 fantasy names w/ tags). Run:  python3 build_coaching_brief.py
"""
import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
prof = json.load(open(os.path.join(HERE, 'offense_profile.json')))
proe = json.load(open(os.path.join(HERE, 'proe_tendency_2026.json')))['teams']
doss = json.load(open(os.path.join(HERE, 'dossier_data.json')))

# teams whose PLAY-CALLER is new in 2026 (from profile identity/playcaller "new" markers)
def is_new(t):
    pc = (prof[t].get('playcaller') or '')
    return 'new' in pc.lower()

by_team = {}
for tm in doss['teams']:
    key = tm.get('team') or (tm['players'][0]['team'] if tm.get('players') else None)
    if key:
        by_team[key] = tm.get('players', [])

TEAM_NAMES = {'ARI':'Arizona Cardinals','ATL':'Atlanta Falcons','BAL':'Baltimore Ravens',
 'BUF':'Buffalo Bills','CAR':'Carolina Panthers','CHI':'Chicago Bears','CIN':'Cincinnati Bengals',
 'CLE':'Cleveland Browns','DAL':'Dallas Cowboys','DEN':'Denver Broncos','DET':'Detroit Lions',
 'GB':'Green Bay Packers','HOU':'Houston Texans','IND':'Indianapolis Colts','JAC':'Jacksonville Jaguars',
 'JAX':'Jacksonville Jaguars','KC':'Kansas City Chiefs','LAC':'Los Angeles Chargers','LAR':'Los Angeles Rams',
 'LA':'Los Angeles Rams','LV':'Las Vegas Raiders','MIA':'Miami Dolphins','MIN':'Minnesota Vikings',
 'NE':'New England Patriots','NO':'New Orleans Saints','NYG':'New York Giants','NYJ':'New York Jets',
 'PHI':'Philadelphia Eagles','PIT':'Pittsburgh Steelers','SEA':'Seattle Seahawks','SF':'San Francisco 49ers',
 'TB':'Tampa Bay Buccaneers','TEN':'Tennessee Titans','WAS':'Washington Commanders'}

out = ["# 2026 Coaching Changes — Detail Brief (v2, regenerated from model)",
       "",
       "**Play-caller-first**: each section leads with WHO CALLS THE PLAYS (HCs who call their own",
       "plays are the entry, regardless of who holds the OC title). Generated by",
       "`build_coaching_brief.py` from `offense_profile.json` + `proe_tendency_2026.json` +",
       "`dossier_data.json` — no hand-maintained facts, so it cannot drift from the model again.",
       ""]

new_teams = sorted([t for t in prof if is_new(t)])
out.append(f"Teams with a new play-caller in 2026: **{len(new_teams)}** — {', '.join(new_teams)}")
out.append("")

for t in new_teams:
    p = prof[t]
    pr = proe.get(t, {})
    ident = p.get('identity', '')
    pace = p.get('pace', {})
    rs = p.get('run_scheme', {})
    env = p.get('environment', {})
    dials = p.get('scheme_dials', {})
    d_str = ', '.join(f"{k}{'+' if v>0 else ''}{v}" for k, v in dials.items()) if dials else '—'
    out.append(f"## {t} — {TEAM_NAMES.get(t, t)}")
    out.append(f"**Play-caller:** {p.get('playcaller','?')}")
    out.append(f"- **Identity:** {ident}")
    out.append(f"- **Tendencies:** pass-rate {p.get('pass_rate','?')}% | PA {p.get('play_action','?')}% | "
               f"motion {p.get('motion','?')}% | pace pctl {pace.get('pctl','?')} "
               f"({pace.get('plays_pg','?')} plays/g) | run: {rs.get('lean','?')} "
               f"(zone {rs.get('zone_rate','?')}%)")
    out.append(f"- **PROE 2026 (model):** {pr.get('proe_2026','?')} "
               f"(2025 actual {pr.get('proe_2025','?')}, carousel {pr.get('carousel_adj','?'):+.1f})"
               if pr.get('carousel_adj') is not None else
               f"- **PROE 2026 (model):** {pr.get('proe_2026','?')}")
    out.append(f"- **Environment:** env {env.get('env_idx','?')}, win total {env.get('win_total','?')} | "
               f"vacated targets {p.get('vacated_tgt_pct','?')}% | dials: {d_str}")
    note = p.get('scheme_note')
    if note:
        out.append(f"- **Scheme note:** {note}")
    outlook = p.get('outlook')
    if outlook:
        out.append(f"- **Outlook:** {str(outlook)[:300]}")
    names = sorted(by_team.get(t, []), key=lambda x: x.get('rank', 9999))[:5]
    if names:
        nm = '; '.join(f"{n['name']} ({n['pos']}, rk{n.get('rank','?')}"
                       + (f", {', '.join(n.get('flags', []))}" if n.get('flags') else '') + ")"
                       for n in names)
        out.append(f"- **Key names:** {nm}")
    out.append("")

path = os.path.join(HERE, 'COACHING_CHANGES_2026_DETAIL.md')
open(path, 'w').write('\n'.join(out) + '\n')
print(f"wrote {path}: {len(new_teams)} teams, {len(out)} lines")
