#!/usr/bin/env python3
"""run_all.py — one-shot orchestrator for the 2026 best-ball deliverables.

Default: rebuild the DOSSIER + FLAGS + RANKINGS chain (fast; depends only on already-built JSON).
  python3 run_all.py
--full : also run the upstream engine + boom subsystem first (needs the raw inputs to be present).
  python3 run_all.py --full
--check: just list which expected outputs currently exist (no run).

Chain (each stage asserts its output exists & is non-empty; fails loud):
  [--full] refactor/pipeline.py   -> features.csv, defense.json, fusion.json ...
  [--full] boom_pipeline.py       -> boom/*.json, command_center.html
  build_coverage_spec.py          -> boom/coverage_route_spec.json  (FP charting 2024+25 per-scheme/route spec)
  build_scheme_fit.py             -> boom/scheme_fit.json     (spec x 2026 schedule, coordinator-aware new-DC)
  build_flag_ranks.py             -> flag_ranks.json          (ADP-anchored nudge; consumes scheme_fit)
  build_dossier.py                -> dossier_data.json        (verified 2026 OL wired in)
  build_lever_count.py            -> lever_count.json         (+ lever_cal/sum into dossier)
  build_flags_layer.py            -> flags_2026.json, flag_rank_delta.csv  (+ flags into dossier)
  build_lever_board.py            -> lever_board.html
  build_rankings.py               -> rankings.html, rankings_2026.csv
  render_dossier.py               -> dossier.html
  build_offense_profile.py        -> offense_profile.json     (offense scheme-identity; also feeds build_home)
  build_team_ceiling.py           -> team_ceiling.json        (needs offense_profile + team_env; must follow build_offense_profile)
  build_slot_paths.py             -> slot_paths.json          (needs flag_ranks + team_ceiling + schedule)
  build_stack_menu.py             -> stack_menu.json          (needs flag_ranks + team_ceiling + schedule)
  render_strategy_board.py        -> draft_strategy_board.html  (consumes strategy_board.json; agent-authored, NOT regenerated)
  integration_audit.py            -> INTEGRATION_AUDIT.md    (FINAL GATE)
  audit_roster_moves.py           -> ROSTER_MOVES_2026.md    (DATA-SIDE FINAL GATE)
"""
import os, sys, subprocess, time, json
HERE=os.path.dirname(os.path.abspath(__file__))
def stage(cmd, outs):
    name=' '.join(cmd); print("==> "+name); t=time.time()
    r=subprocess.run([sys.executable]+cmd, cwd=HERE, capture_output=True, text=True)
    if r.returncode!=0: sys.exit("[FAIL] %s\n%s"%(name, r.stderr[-2000:]))
    for o in outs:
        p=os.path.join(HERE,o)
        if not (os.path.exists(p) and os.path.getsize(p)>0): sys.exit("[FAIL] %s: missing/empty %s"%(name,o))
    tail=(r.stdout.strip().splitlines() or [''])[-1]
    print("    ok (%.1fs) %s  %s"%(time.time()-t, outs, tail[:80]))
DOSSIER=[(["build_coverage_spec.py"],["boom/coverage_route_spec.json"]),   # FP charting 2024+25 -> per-scheme/route spec
 (["build_scheme_fit.py"],["boom/scheme_fit.json"]),                       # spec x 2026 schedule (coordinator-aware new-DC)
 (["build_flag_ranks.py"],["flag_ranks.json"]),                            # ADP-anchored nudge (consumes scheme_fit)
 (["build_dossier.py"],["dossier_data.json"]),
 (["build_lever_count.py"],["lever_count.json"]),
 (["build_flags_layer.py"],["flags_2026.json","flag_rank_delta.csv"]),
 (["build_lever_board.py"],["lever_board.html"]),
 (["build_rankings.py"],["rankings.html","rankings_2026.csv"]),
 (["build_adp_clusters.py"],["adp_cluster_board.html"]),   # "best pick per ADP cluster" board (reads flag_ranks) -- was off-pipeline + going stale
 (["build_big_board.py"],["big_board_2026.html"]),         # 2026 big board view of adj_rank -- was off-pipeline + going stale
 (["render_dossier.py"],["dossier.html"]),
 (["build_dossier_deep.py"],["dossier_deep.html"]),   # analyst-narrative + media + EPA deep-dive (was orphaned -> now kept fresh)
 (["build_offense_profile.py"],["offense_profile.json"]),  # offense scheme-identity layer -> build_home.py (home.html landing; build_home itself is run manually, so keep its input fresh here)
 (["build_team_ceiling.py"],["team_ceiling.json"]),     # needs offense_profile + team_env + coordinator scheme -> must follow build_offense_profile
 (["build_slot_paths.py"],["slot_paths.json"]),          # needs flag_ranks + team_ceiling + schedule
 (["build_stack_menu.py"],["stack_menu.json"]),          # needs flag_ranks + team_ceiling + schedule
 (["render_strategy_board.py"],["draft_strategy_board.html"]),  # consumes strategy_board.json (agent-authored, NOT regenerated by chain)
 (["integration_audit.py"],["INTEGRATION_AUDIT.md"]),  # FINAL GATE: flags any layer built-but-not-consumed (orphans, ignored fields, divergences)
 (["audit_roster_moves.py"],["ROSTER_MOVES_2026.md"])]  # DATA-SIDE FINAL GATE: cross-source team check + roster-move reconciliation (real move = all sources agree; mis-join = they disagree)
FULL=[(["refactor/pipeline.py"],["features.csv","defense.json"]),(["boom_pipeline.py"],["boom/boom_marks.json"])]
def main():
    chain=(FULL+DOSSIER) if "--full" in sys.argv else DOSSIER
    if "--check" in sys.argv:
        for cmd,outs in chain:
            miss=[o for o in outs if not (os.path.exists(os.path.join(HERE,o)) and os.path.getsize(os.path.join(HERE,o))>0)]
            print("  [%s] %-26s %s%s"%('OK ' if not miss else 'MISS',' '.join(cmd),outs,(' MISSING %s'%miss) if miss else ''))
        return
    t0=time.time()
    for cmd,outs in chain: stage(cmd,outs)
    dd=json.load(open(os.path.join(HERE,'dossier_data.json'))); fl=json.load(open(os.path.join(HERE,'flags_2026.json')))
    print("\nDONE in %.1fs — %d teams, %d players, %d flagged (%d playoff). Open: dossier.html, rankings.html, lever_board.html"%(
        time.time()-t0,len(dd['teams']),sum(len(t['players']) for t in dd['teams']),fl['meta']['n_flagged'],fl['meta']['n_playoff_flagged']))
if __name__=='__main__': main()
